export const data = [
    { label: 'CAD', name: 'Canadian Dollar' },
    { label: 'HKD', name: 'Hong Kong Dollar' },
    { label: 'ISK', name: 'Iceland Krona' },
    { label: 'PHP', name: 'Philippine Peso' },
    { label: 'DKK', name: 'Danish Krone' },
    { label: 'HUF', name: 'Venger Forint' },
    { label: 'CZK', name: 'Czech Koruna' },
    { label: 'AUD', name: 'Australian Dollar' },
    { label: 'RON', name: 'Romanian Leu' },
    { label: 'SEK', name: 'Swedish Krona' },
    { label: 'IDR', name: 'Indonesian Rupiah' },
    { label: 'INR', name: 'Indian Rupee' },
    { label: 'BRL', name: 'Brazilian Real' },
    { label: 'RUB', name: 'Russian Ruble' },
    { label: 'HRK', name: 'Croatian Kuna' },
    { label: 'JPY', name: 'Japanese Yen' },
    { label: 'THB', name: 'Thailand Baht' },
    { label: 'CHF', name: 'Swiss Franc' },
    { label: 'EUR', name: 'EURO' },
    { label: 'SGD', name: 'Singapore Dollar' },
    { label: 'PLN', name: 'Polish Zloty' },
    { label: 'BGN', name: 'Bulgarian Lev' },
    { label: 'TRY', name: 'Turkish Lira' },
    { label: 'CNY', name: 'Yuan Renminbi' },
    { label: 'NOK', name: 'Norwegian Krone' },
    { label: 'NZD', name: 'New Zealand Dollar' },
    { label: 'ZAR', name: 'Namibian Rand' },
    { label: 'USD', name: 'US Dollar' },
    { label: 'MXN', name: 'Mexican Peso' },
    { label: 'ILS', name: 'New Israeli Sheqel' },
    { label: 'GBP', name: 'Pound Sterling' },
    { label: 'KRW', name: 'South Korean Won' },
    { label: 'MYR', name: 'Malaysian Ringit' }
];
